- name: Prometheus Server
  ansible.builtin.import_tasks:
    file: server.yml
  when: prometheus_server

- name: node exporter
  ansible.builtin.import_tasks:
    file: export.yml
  when: node_exporter