- name: Install python
  ansible.builtin.yum:
    name:
      - python36
      - gcc
      - python3-devel
    state: installed

- name: App Pre-requisites
  ansible.builtin.import_tasks:
    file: app-prereq.yml

- name: Install python dependencies.
  ansible.builtin.pip:
    requirements: /app/requirements.txt
    executable: pip3.6

- name: Systemd Setup
  ansible.builtin.import_tasks:
    file: systemd-setup.yml
