- name: Mongodb Schema
  when: schema_type == "mongo"
  block:
    - name: Copy mongodb repo file
      ansible.builtin.copy:
        src: mongodb.repo
        dest: /etc/yum.repos.d/mongodb.repo

    - name: Install mongo client
      ansible.builtin.yum:
        name: mongodb-org-shell
        state: installed

    - name: Download MongoDB Pem file
      ansible.builtin.get_url:
        url: https://s3.amazonaws.com/rds-downloads/rds-combined-ca-bundle.pem
        dest: /app/rds-combined-ca-bundle.pem

    ansible.builtin.shell: mongo --ssl --host {{ lookup('amazon.aws.aws_ssm', '{{env}}.docdb.endpoint', region='us-east-1') }}:27017 --sslCAFile /app/rds-combined-ca-bundle.pem --username {{ lookup('amazon.aws.aws_ssm', '{{env}}.docdb.user', region='us-east-1') }} --password {{ lookup('amazon.aws.aws_ssm', '{{env}}.docdb.pass', region='us-east-1') }} </app/schema/{{component}}.js

- name:  Mysql Schema
  when: schema_type == "mysql"
  block:
    - name: Install mysql client
      ansible.builtin.yum:
        name: mysql
        state: installed

    - name: Load Schema
      ansible.builtin.shell: mysql -h mysql-dev.devops517test.online -uroot -pRoboShop@1 < /app/schema/{{ component }}.sql